### ISSUE TITLE
Tag 3.10 release on Releases page?

### ISSUE THREAD

**Issue by richb-hanover** [timestored/qstudio#100]
You've released 3.10 on the [Downloads](https://www.timestored.com/qstudio/download) page. 

It would be good to add it to the [Releases](https://github.com/timeseries/qstudio/releases) page, and update the CHANGELOG to mention the new version. Thanks

**Comment by ryanhamilton** [comment]
Hi Rich,

THanks for this and the other issues.
I really appreciate all the issues and feedback you are providing.

How about we hop on a zoom call?

I would like to hear how you are using qStudio. You can tell me or even show me the most annoying issues "in person".
I would also like to share my thoughts and roadmap so you can see what I'm working on and what I'm currently not.

My email is RYAN ([AT]) timestored.com just email me or pick a time slot here:
https://calendly.com/timestored/pulse?month=2024-10&date=2024-10-07

**Comment by ryanhamilton** [comment]
Released 4.01
