### ISSUE TITLE
Version 3.81? You've been busy!

### ISSUE THREAD

**Issue by richb-hanover** [timestored/qstudio#107]
I see that the [Downloads](https://www.timestored.com/qstudio/download) page is now showing version 3.81. Thanks for documenting your tests in Issue #105

But the main Github page still shows release 3.06 - that seems like ancient history.

Would you please update the CHANGELOG file and the Releases page to reflect all this good work? (Nobody knows about it if we don't tell them.) Many thanks.

**Comment by ryanhamilton** [comment]
Hi Rich,
I'm trying to get a number of very big changes out, as soon as I have the notepad released I'm going to fix some of your smaller issues or look again at the MAC in general.

**Comment by richb-hanover** [comment]
Excellent! I'll look forward to the Notepad...

**Comment by ryanhamilton** [comment]
Done
