### ISSUE TITLE
Allow toggling series in chart

### ISSUE THREAD

**Issue by ryanhamilton** [timestored/qstudio#109]
user-kent

User performed time-series chart and expected to be able to toggle what columns were visible from the UI.
Seems reasonable.

**Comment by timeseries** [comment]
+ user-andrew

**Comment by ryanhamilton** [comment]
![394249314-7aea151d-35bd-40ae-b879-96ea60a8aa67](https://github.com/user-attachments/assets/ecacc211-259a-426a-8950-0b1cd5180a9f)
