### ISSUE TITLE
Fully Open Source qStudio

### ISSUE THREAD

**Issue by ryanhamilton** [timestored/qstudio#43]
qStudio could currently be described as Free and Open core, in 2022 I did a large conversion of a lot of the code but gave up from sheer boredom. To make sure there is demand and to motivate myself, I am going to convert at least one file for every user that posts here.

Please 

**1. Star the project.
2. Comment on this page.
3. I will then open source at least one source file and reply back.**

The greater the demand, the faster it get's done :)

**Comment by pepas-everly** [comment]
> in 2022 I did a large conversion of a lot of the code but gave up from sheer boredom.

What is involved in "converting" the code?  For me, this would be `git add .`

**Comment by ryanhamilton** [comment]
1. I've added clients and users names/emails in comments places where a fix was specific to their issue.
2. I want to ensure comments don't contain anything I don't want public. When I wrote them, they were definitely written only to be read by me and one other person.
3. One niche database is charged for, I need to move that code to a separate package.
4. The signing keys are in my own personal source repo. I need to workout github secrets and how to do a build with those keys.
That's the ones I can think of. I'm more worried about what I can't remember.

**Comment by ryanhamilton** [comment]
Thanks @pepas-everly  for commenting and starring.
I've added the open source for 9 source files: https://github.com/timeseries/qstudio/commit/710b0f327b80cfe05b7b0ace5024f258ed3e0cbd

**Comment by dopeboy** [comment]
This is amazing, Ryan. Thank you for doing this.

**Comment by ryanhamilton** [comment]
Thanks @dopeboy  
Open sourced and relicensed 6 files: https://github.com/timeseries/qstudio/commit/95cfefff7a2970cb197f80e6eb783e58a101592d

**Comment by ethack** [comment]
I just heard about qStudio and an Android to give it a shot. Pretty cool how it's cross platform and supports the OLAP databases I use.

**Comment by DanFitzgibbon** [comment]
Thank you for the **insane** amount of effort and love! Would love to be able to use this in Databricks SQL Warehouses and might just be tempted to help add that as well, if possible.

**Comment by ryanhamilton** [comment]
THanks @ethack  - Open soured 3 files in tscore: https://github.com/timeseries/qstudio/commit/f040c7d3e4fb94a4922154f9c18018880d1299b1

**Comment by ryanhamilton** [comment]
Thanks @DanFitzgibbon  - Opened messages https://github.com/timeseries/qstudio/commit/fb6641a063f18c3ecded868982a1cb1ec1860ef1 - Mental +1 for databricks SQL.

**Comment by prabhu** [comment]
Brilliant idea! Boredom is the number 1 productivity killer for everyone including open-source devs and community can certainly help with motivation and support! This is a cool project, which I might use personally. Keep up the good work!

**Comment by ryanhamilton** [comment]
Thanks @prabhu  - jgrowl open sourced: https://github.com/timeseries/qstudio/commit/044367b12975a95afcd9f1f8bdc1eafd2c60f85e

**Comment by richb-hanover** [comment]
I already star'ed the repo - a while back. But I'm really happy now that qStudio includes PRQL. It lets me write [fancy PRQL queries](https://github.com/TaxFairness/TaxFairness/blob/main/PRQL_Queries/CleanScrapedDataView.prql) that generate a ton of SQL without knowing a heckuva lot about the SQL language. I edit the query, hit Cmd-E (Ctl-E on Windows) and Presto! I can see if the query did what I expected. I'm looking forward to more enhancements. Thanks!

**Comment by ryanhamilton** [comment]
Restarting on this effort NOW.

**Comment by richb-hanover** [comment]
Great news. 

I just want to say how much fun I've had (and the good work I've been able to accomplish) using qStudio and PRQL together. As I mentioned, I'm documenting some of it in my [qStudio PRQL Quick Start](https://github.com/richb-hanover/qStudio-PRQL_Quick_Start). There are still hitches/infelicities (see Lesson 3), but it's working great once you learn to avoid them. Thanks.

**Comment by ryanhamilton** [comment]
This is now done :)

**Comment by richb-hanover** [comment]
@ryanhamilton Congratulations! This is very exciting. I bundled 4.01 into my macOS app - it's available at https://randomneuronsfiring.com/wp-content/uploads/qStudio.zip

In addition, I placed the cleaned-up qStudio.svg icon in https://github.com/richb-hanover/create-qstudio-macos-app/blob/main/qStudio%20Icons%20from%20Fiverr/Icon(Transparent%20Background).svg

(That repo has the script that builds the macOS app bundle, too.) Thanks!
